### PR TITLE
add build script, tests, cli, api and 100% coverage

### PR DESCRIPTION
**Pull request by tunnckoCore**
`cssProperties()` is async function (which live in `build.js`) or return array with all properties if dont have arguments.
Through CLI can update/build list of all available (170+) CSS2/3 css properties, scraped from W3C website

- add more tests
- add cli
- add async function
- update travis to run coverage
- add coverage
- add `bin` in pkg json
- add more scripts for automation

### CODE REVIEW

**Comment by tunnckoCore** [comment]
`css-properties --help` for more info

**Comment by tunnckoCore** [comment]
currently properties are 178

**Comment by johnotander** [comment]
This is rad! Thanks @tunnckoCore

**Comment by johnotander** [comment]
Published as `npm@0.1.0`

**Comment by tunnckoCore** [comment]
Thanks! :) Is there more something for v1.0.0? Cuz for sure I want v1.0.0 for `filter-css-properties`

**Comment by johnotander** [comment]
Nope. Published to npm as `css-properties@1.0.0`.

**Comment by tunnckoCore** [comment]
Great :+1:

**Pull request merged**
